// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nntzunqyvtmejeefcxnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5udHp1bnF5dnRtZWplZWZjeG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTMxMjksImV4cCI6MjA2OTU2OTEyOX0.2BPxBNZT4ZqoI8KKFTVLJ9dYXc0lsiXbnbvoq60p4Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});